services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Jvelletti\JveUpgradewizard\:
    resource: '../Classes/*'

  Jvelletti\JveUpgradewizard\Command\UpdateFilesCommand:
    tags:
      - name: 'console.command'
        command: 'jvelletti:updatefiles'
        schedulable: false
  Jvelletti\JveUpgradewizard\Command\RepairPrimaryKeyCommand:
    tags:
      - name: 'console.command'
        command: 'jvelletti:repairprimarykey'
        schedulable: false
  Jvelletti\JveUpgradewizard\Command\ApproveXLFCommand:
    tags:
      - name: 'console.command'
        command: 'jvelletti:approvexlf'
        schedulable: false